spring.application.name=bdget

# Deshabilitar Config Server para correr en local
spring.config.import=optional:configserver:
spring.cloud.config.enabled=false
spring.cloud.config.fail-fast=false

# Logs
logging.level.root=INFO
logging.level.org.hibernate=DEBUG
logging.level.org.springframework=DEBUG

# Base de datos Oracle (se sobreescribe con variables de entorno en docker-compose)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@s2eazr8t9kfhqm3e_tp?TNS_ADMIN=/app/wallet}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:java_bd}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ClaseFullStack1-}
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none

# Pool de conexiones
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000

# Puerto
server.port=8085